tag: ""
random_seed: 42

##############
# Dataloader #
##############
dataloader:
  # "arithmetic", "algebraic", "boolean" 
  dataset: "arithmetic"
  # len_expression: 10
  num_workers: 0

#########
# Model #
#########
model:
  # type: convmixer, mlpmixer, cnn, transformer
  type: "transformer"
  num_blocks: 1
  embedding_dim: 32
  expansion_factor: 1  # MLP-Mixer / Transformer
  kernel_size: 3       # ConvMixer / CNN
  dropout_prob: 0
  position_embedding:
    # Select from: ones, zeros, random_normal, sinusoidal
    encoding: "ones" 
  self_attention:  # Transformer only
    num_heads: 4  # head_dim = embedding_dim // n_heads
  mask:  # Transformer only
    is_activated: true
    is_trainable: true
    # Select from: trainable_additive, trainable_multiplicative 
    type: "trainable_multiplicative" 


###########
# Trainer #
###########
trainer:
  # gpu, cpu
  device: "gpu"
  num_update_steps: 10000000
  batch_size: 128
  learning_rate: 3.0e-4
  weight_decay: 0
  gradient_clipping:
    is_activated: false
    max_norm: 1.0

load_model:
  is_activated: false 
  model_name: "arithmetic"
  model_path: -1

########
# Data #
########
data:
  n_classes: Null
  input_shape: Null

###########
# Summary #
###########
summary:
  save_train_stats:
    every_n_updates: 100
  save_test_stats:
    every_n_updates: -1
  save_model:
    every_n_updates: 1000
  add_position_embeddings:
    every_n_updates: 1000
  add_token_embeddings:
    every_n_updates: 1000
  add_linear_weights:
    every_n_updates: 1000
  add_mask_weights:
    every_n_updates: 1000
  add_graph: false

###############
# Directories #
###############
dirs:
  data: "data"
  runs: "runs"
  weights: "weights"
